### PR TITLE
This fix cleanup: models, Commands. Constants moved to dedicated file Updated composer json file.

### PR DESCRIPTION
**Pull request by tirjok**

### CODE REVIEW

**Comment by ptondereau** [comment]
Nice work @tirjok  but what about to extract constants into crm-launcher.php config file ?

**Comment by tirjok** [comment]
For simplicity and easy to read i added a dedicated file for constants. We may use config file also, it may loose code readability.

**Comment by ptondereau** [comment]
Readability, I don't think so :/ 
Imagine if DB credentials was not in a config file and in define. That's the same reflexion.

**Comment by tirjok** [comment]
@ptondereau Please explain more.

**Comment by ptondereau** [comment]
DB credentials are placed in config file for a good reason and not in defines. I'm not a fan of define options. In general, I prefer to put global constants in config file for concern

**Comment by tirjok** [comment]
Or we can use a constants class rather than a file. Because value in configuration file is harder to maintain than value in constants class, because the compiler does not check it exists and is of correct type, the IDE usually does not provide code assistance for it and also because it's yet another syntax you have to switch to while programming.

**Comment by ptondereau** [comment]
I understand your point. Let the author to decide for now. Thanks for the debat

**Comment by rubenwouters** [comment]
I like the idea to extract constants to the config file. But then again: these constants are not made to be edited/changed to another value like DB credentials are. 

Honestly I'm not sure what's the best approach. 

Thoughts?

**Comment by jorenvh** [comment]
I would not use constants for this. The values are not ment to change.

**Pull request closed without merging**
